In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [13]:
import torch 
n=torch.FloatTensor([1,2,3,4,5,6])
print(n)

tensor([1., 2., 3., 4., 5., 6.])


In [14]:
import torch 
x=torch.arange(0,9)
x
y=x.view(3,3)
y

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [15]:
import numpy as np
x_input = np.random.sample((1,2))
print(x_input)


[[0.60140061 0.21819117]]


In [16]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
x=tf.placeholder("float",shape=[1,2],name='x')


In [17]:
tf.data.Dataset.from_tensor_slices
dataset= tf.data.Dataset.from_tensor_slices(x)


In [18]:
iterator = dataset.make_initializable_iterator()
get_next = iterator.get_next()


In [19]:
#execution
with tf.Session() as session:
    session.run(iterator.initializer,feed_dict={x:x_input})
    print(session.run(get_next))


[0.6014006  0.21819118]
